### PR TITLE
Chat notify when burrowing with block

### PR DESCRIPTION
**Pull request by phobologicalt**
if i fucked it up tell me and ill fix, just thought this was cool :D (im not good at java btw)

### CODE REVIEW

**Comment by ChompChompDead** [comment]
Why

**Comment by phobologicalt** [comment]
> Why

i thought it was cool :,(

**Comment by Officer32k** [comment]
hmmmm

**Comment by Officer32k** [comment]
idk

**Comment by Officer32k** [comment]
we can't do this one do something else

**Comment by Officer32k** [comment]
ehhhhhh nvm idk looks fine ill remove it if i need to

**Pull request merged**
